[package]
name = "messages"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
postcard = { workspace = true, features = ["heapless"] }
