[package]
name = "host_tui"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
bytes = { workspace = true }
chrono = { workspace = true }
color-eyre = { workspace = true }
crossterm = { workspace = true, features = ["event-stream"] }
futures = { workspace = true }
postcard.workspace = true
ratatui = { workspace = true }
sc_messages = { path = "../sc_messages" }
tokio = { workspace = true }

# Read the optimization guideline for more details: https://ratatui.rs/recipes/apps/release-your-app/#optimizations
[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
