[package]
name = "host_tui"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
bytes = { workspace = true }
cfg-if = { workspace = true }
chrono = { workspace = true }
color-eyre = { workspace = true }
crossterm = { workspace = true, features = ["event-stream"] }
futures = { workspace = true }
postcard = { workspace = true }
ratatui = { workspace = true }
sc_messages = { path = "../sc_messages" }
tokio = { workspace = true }

[lints]
workspace = true
