[workspace]
resolver = "3"
members = ["host_tui", "messages"]
exclude = ["cross/*"]

[workspace.package]
edition = "2024"
license = "MIT"

[workspace.dependencies]
serde = { version = "1.0.228", default-features = false }
postcard = { version = "1.1.3", default-features = false }
