[workspace]
resolver = "3"
members = ["host_tui", "sc_messages"]
exclude = ["cross/*"]

[workspace.package]
edition = "2024"
license = "MIT"

[workspace.dependencies]
serde = { version = "1.0.228", default-features = false }
postcard = { version = "1.1.3", default-features = false }
ratatui = "0.30.0"
color-eyre = "0.6.5"
crossterm = "0.29.0"
futures = "0.3.31"
tokio = { version = "1.49.0", features = ["full"] }
bytes = "1.11.0"
chrono = "0.4.43"
zeroize = { version = "1.8.2", default-features = false }
